---
redis:
  ip: 192.168.56.103
  port: 6379
  passwd: 123456
  db: 0
plugins:
- applehealthcheck2dk
- applehealthcheck2apple
- real-ip
- ai
- client-control
- proxy-control
- request-id
- zipkin
- ext-plugin-pre-req
- fault-injection
- mocking
- serverless-pre-function
- cors
- ip-restriction
- ua-restriction
- referer-restriction
- csrf
- uri-blocker
- request-validation
- chaitin-waf
- multi-auth
- openid-connect
- cas-auth
- authz-casbin
- authz-casdoor
- wolf-rbac
- ldap-auth
- hmac-auth
- basic-auth
- jwt-auth
- jwe-decrypt
- key-auth
- consumer-restriction
- attach-consumer-label
- forward-auth
- opa
- authz-keycloak
- proxy-cache
- body-transformer
- ai-prompt-template
- ai-prompt-decorator
- ai-prompt-guard
- ai-rag
- ai-rate-limiting
- ai-proxy-multi
- ai-proxy
- ai-aws-content-moderation
- proxy-mirror
- proxy-rewrite
- workflow
- api-breaker
- limit-conn
- limit-count
- limit-req
- gzip
- traffic-split
- redirect
- response-rewrite
- mcp-bridge
- degraphql
- kafka-proxy
- grpc-transcode
- grpc-web
- http-dubbo
- public-api
- prometheus
- datadog
- lago
- loki-logger
- elasticsearch-logger
- echo
- loggly
- http-logger
- splunk-hec-logging
- skywalking-logger
- google-cloud-logging
- sls-logger
- tcp-logger
- kafka-logger
- rocketmq-logger
- syslog
- udp-logger
- file-logger
- clickhouse-logger
- tencent-cloud-cls
- inspect
- example-plugin
- aws-lambda
- azure-functions
- openwhisk
- openfunction
- serverless-post-function
- ext-plugin-post-req
- ext-plugin-post-resp
- ai-request-rewrite
etcd:
  prefix: /apisix
  host:
  - http://127.0.0.1:2379
  watch_timeout: 50
  startup_retry: 2
  tls:
    verify: true
  timeout: 30
graphql:
  max_size: 1048576
deployment:
  etcd:
    prefix: /apisix
    host:
    - http://127.0.0.1:2379
    watch_timeout: 50
    startup_retry: 2
    tls:
      verify: true
    timeout: 30
  role: traditional
  config_provider: etcd
  role_traditional:
    config_provider: etcd
  admin:
    enable_admin_cors: true
    admin_api_version: v3
    admin_listen:
      port: 9180
      ip: 0.0.0.0
    admin_key:
    - key: nxXfKvqABLKnXvDowATILigoUPiXdunF
      role: admin
      name: admin
    allow_admin:
    - 127.0.0.0/24
    enable_admin_ui: true
    admin_key_required: true
nginx_config:
  main_configuration_snippet: ''
  http_configuration_snippet: ''
  http_server_configuration_snippet: ''
  http_server_location_configuration_snippet: ''
  http_admin_configuration_snippet: ''
  http_end_configuration_snippet: ''
  error_log_level: warn
  worker_processes: auto
  enable_cpu_affinity: false
  worker_rlimit_nofile: 20480
  worker_shutdown_timeout: 240s
  event:
    worker_connections: 10620
  max_pending_timers: 16384
  max_running_timers: 4096
  meta:
    lua_shared_dict:
      standalone-config: 10m
      prometheus-metrics: 15m
      status-report: 1m
  http:
    upstream:
      keepalive_timeout: 60s
      keepalive_requests: 1000
      keepalive: 320
    access_log_buffer: 16384
    keepalive_timeout: 60s
    client_header_timeout: 60s
    client_body_timeout: 60s
    client_max_body_size: 0
    send_timeout: 10s
    underscores_in_headers: 'on'
    real_ip_header: X-Real-IP
    real_ip_recursive: 'off'
    enable_access_log: true
    access_log: logs/access.log
    proxy_ssl_server_name: true
    access_log_format: $remote_addr - $remote_user [$time_local] $http_host "$request"
      $status $body_bytes_sent $request_time "$http_referer" "$http_user_agent" $upstream_addr
      $upstream_status $upstream_response_time "$upstream_scheme://$upstream_host$upstream_uri"
    charset: utf-8
    access_log_format_escape: default
    variables_hash_max_size: 2048
    lua_shared_dict:
      cas-auth: 10m
      ocsp-stapling: 10m
      plugin-limit-req-redis-cluster-slot-lock: 1m
      plugin-limit-req: 10m
      plugin-limit-count: 10m
      plugin-limit-count-redis-cluster-slot-lock: 1m
      internal-status: 10m
      upstream-healthcheck: 10m
      worker-events: 10m
      lrucache-lock: 10m
      balancer-ewma: 10m
      balancer-ewma-locks: 10m
      balancer-ewma-last-touched-at: 10m
      etcd-cluster-health-check: 10m
      plugin-ai-rate-limiting: 10m
      plugin-ai-rate-limiting-reset-header: 10m
      plugin-limit-conn: 10m
      plugin-limit-conn-redis-cluster-slot-lock: 1m
      mcp-session: 10m
      prometheus-metrics: 10m
      ext-plugin: 1m
      access-tokens: 1m
      introspection: 10m
      jwks: 1m
      discovery: 1m
      plugin-api-breaker: 10m
      tracing_buffer: 10m
      tars: 1m
    custom_lua_shared_dict:
      apple-healthcheck: 10m
    real_ip_from:
    - 127.0.0.1
    - 'unix:'

  stream:
    access_log: logs/access_stream.log
    access_log_format: $remote_addr [$time_local] $protocol $status $bytes_sent $bytes_received
      $session_time
    lua_shared_dict:
      worker-events-stream: 10m
      tars-stream: 1m
      upstream-healthcheck-stream: 10m
      etcd-cluster-health-check-stream: 10m
      lrucache-lock-stream: 10m
      plugin-limit-conn-stream: 10m
    access_log_format_escape: default
    enable_access_log: false
  stream_configuration_snippet: ''
  error_log: logs/error.log
apisix:
  enable_server_tokens: true
  disable_sync_configuration_during_start: false
  node_listen:
  - 9080
  enable_dev_mode: false
  enable_reuseport: true
  enable_ipv6: true
  extra_lua_path: 'carkey/third_part/?.lua'
  extra_lua_cpath: ''
  enable_admin: true
  enable_resolv_search_opt: true
  resolver_timeout: 5
  events:
    module: lua-resty-events
  data_encryption:
    enable_encrypt_fields: true
    keyring:
    - qeddd145sfvddff3
    - edd1c9f0985e76a2
  show_upstream_status_in_response_header: true
  enable_control: true
  proxy_mode: http
  normalize_uri_like_servlet: false
  delete_uri_tail_slash: false
  proxy_cache:
    zones:
    - memory_size: 50m
      disk_size: 1G
      disk_path: /tmp/disk_cache_one
      name: disk_cache_one
      cache_levels: '1:2'
    - memory_size: 50m
      name: memory_cache
    cache_ttl: 10s
  enable_http2: true
  ssl:
    listen:
    - port: 9443
      enable_http3: false
    ssl_trusted_certificate: /etc/ssl/certs/ca-certificates.crt
    enable: true
    ssl_session_tickets: false
    ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl_protocols: TLSv1.2 TLSv1.3
  router:
    http: radixtree_host_uri
    ssl: radixtree_sni
plugin_attr:
  applehealthcheck2apple:
    endpoint:
      - cn-apple-pay-gateway-cert.apple.com
      - cn-apple-pay-gateway-cert-smp.apple.com
      - cn-apple-pay-gateway-sh-pod1.apple.com
      - cn-apple-pay-gateway-sh-pod2.apple.com
      - cn-apple-pay-gateway-sh-pod3.apple.com
      - cn-apple-pay-gateway-tj-pod1.apple.com
      - cn-apple-pay-gateway-tj-pod2.apple.com
      - cn-apple-pay-gateway-tj-pod3.apple.com
    tls:
      cert_path: /workspace/carkey/third_part/apisix/plugins/apple-client.pem
      key_path: /workspace/carkey/third_part/apisix/plugins/apple-client.key
  proxy-mirror:
    timeout:
      read: 60s
      send: 60s
      connect: 60s
  log-rotate:
    timeout: 10000
    interval: 3600
    max_size: -1
    max_kept: 168
    enable_compression: false
  inspect:
    hooks_file: /usr/local/apisix/plugin_inspect_hooks.lua
    delay: 3
  skywalking:
    report_interval: 3
    service_name: APISIX
    endpoint_addr: http://127.0.0.1:12800
    service_instance_name: APISIX Instance Name
  dubbo-proxy:
    upstream_multiplex_count: 32
  zipkin:
    set_ngx_var: false
  opentelemetry:
    collector:
      request_headers:
        Authorization: token
      address: 127.0.0.1:4318
      request_timeout: 3
    resource:
      service.name: APISIX
    trace_id_source: x-request-id
    set_ngx_var: false
    batch_span_processor:
      drop_on_queue_full: false
      max_queue_size: 1024
      batch_timeout: 2
      inactive_timeout: 1
      max_export_batch_size: 16
  server-info:
    report_ttl: 60
  prometheus:
    export_addr:
      port: 9091
      ip: 127.0.0.1
    metric_prefix: apisix_
    enable_export_server: true
    export_uri: /apisix/prometheus/metrics
stream_plugins:
- ip-restriction
- limit-conn
- mqtt-proxy
- syslog
...
